* Market intervention and surplus
  - Surplus is generated by trade, CS (Consumer Surplus) and PS (Producer Surplus) are 
    created by trading. The net benefit of participating in the market is the addition of the two.
  - Surplus loss is deadweight loss. You get DWL with:
     - _too few trades_: less economic surplus, you give up trades when marginal benifit is greater than
       cost. If you institude a price floor where the price can't go below a price, there is a reduction 
       in the number of trades. People are willing to pay for the next unit, but lless than the price floor.
       This also redistributes surplus, which is an equity rather than an efficiency issue. 
     - Producing too much makes Marginal Cost exceed Marginal Benifit, the net benifit decreases. Here there is
       too much being produced. The trade is made in a way reducing benifit. Total surplus then decreases. If we 
       produce at a quantity above the equilibrium, benifit is the area under the demand curve. However, 
       the total cost is the area under the supply curve, which results in an area where total cost exceeds benifit
       and we get deadweight loss. The cost is greater than the benifit. A unit past the efficient point costs more
       than the benifit it gives to consumers. 
     - We need the right quantity and allocation of goods. In the market, only people buying are people with marginal benifit
       equal to or greater than the price. Likewise, the sellers are selling only if their cost is less than the market price.
  - Market equilibrium quantity is necessary for efficiency. So is allocation of selling and buying. 
  - Price controls
    - Price ceilings
      - Maximum rent
    - Price floors 
      - Minimum wage
    - Price controls result in inefficient allocation, lack/excess of quality. 
  - Quantity controls
    - Quotas
    - Licenses
  - Subsidies
  - Excise tax - a tax on a specific good. 
    - If you raise the price of a good, the cost of selling a soda goes up. The way to model this is to shift
      the supply curve upwards by the amount of the tax. Which means that, in order for the price to go up by that amount
      at the equilibrium price, demand would have to be inelastic. However, demand isn't inelastic and part of the tax
      is passed back to the producer because they won't sell as much. There is now a 'tax wedge'. There is now a deadweight 
      loss, between where the market price would be and is. Part of the surplus goes to the government, and the producer and
      consumer surplus is smaller. If there is a more responsive market, teh change in quantity is larger. 
  - Price elasticity Definition: the responsiveness of quantity to a change in price.
    - epsilon = %(change in quantity demanded)/(%change in proce) = 1/slope*P/Q. This is the derivative of demand with respect to price. 
      the change in price divided by the change in quantity. The steeper a curve, the less elastic. A very steep demand curve is not very elasic.
      So if your supply curve goes up, i.e. things cost more, there is a smaller change in quantity and a smaller amount of deadweight loss.
    - there is always a tradeoff between efficiency and equity. 
  - Tax incidence: ('who really pays')
    - Incidence of the tax does not depend on whether the tax is placed on buyers or sellers.
    - Statutory incidence is who the government says is paying it.
    - Incidence of the tax depends on somethign.
    - It doesn't matter who the government says pays the tax, both parties (producers and sellers) pay the tax. As your demand curve gets steeper
      consumers pay more and more of the tax. Producers want to add the full amount of tax. The producers can shove this onto the consumers, who 
      only have one way to avoid it: not paying for it, not buying, which forces a drop in the price. Responsiveness to a change in price
      determines how much you pay. 

